const questionFlows = {
  new_revenue: [
    {
      question_id: 'q1',
      question_text: 'What type of revenue impact does this initiative create?',
      help_text: 'Most corporate AI initiatives fall into one of these categories.',
      input_type: 'select',
      options: ['New revenue stream', 'Cost savings / efficiency', 'Churn reduction / retention'],
      default_value: 'New revenue stream',
      parameter_key: 'revenueModel',
      mapValue: v => ({ 'New revenue stream': 'new_revenue', 'Cost savings / efficiency': 'cost_savings', 'Churn reduction / retention': 'churn_reduction' }[v] || 'new_revenue'),
    },
    {
      question_id: 'q2',
      question_text: 'What is your current customer or user base?',
      help_text: 'Swiss B2B companies typically serve 50-500 enterprise clients. B2C platforms may have 10K-500K users.',
      input_type: 'number',
      default_value: 200,
      min: 1,
      max: 10000000,
      step: 10,
      unit: 'customers',
      parameter_key: 'baseCustomers',
    },
    {
      question_id: 'q3',
      question_text: 'What monthly revenue do you expect per customer?',
      help_text: 'Enterprise SaaS in Switzerland typically ranges CHF 200-5,000/month per customer.',
      input_type: 'number',
      default_value: 500,
      min: 1,
      max: 100000,
      step: 50,
      unit: 'CHF',
      parameter_key: 'revenuePerCustomer',
    },
    {
      question_id: 'q4',
      question_text: 'What monthly growth rate do you expect?',
      help_text: 'Healthy B2B growth is 3-8% monthly. AI-driven products often see 5-15% in early stages.',
      input_type: 'slider',
      default_value: 5,
      min: 0,
      max: 30,
      step: 1,
      unit: '%',
      parameter_key: 'growthRate',
      mapValue: v => v / 100,
    },
    {
      question_id: 'q5',
      question_text: 'What are your expected monthly operating costs?',
      help_text: 'Include team salaries, infrastructure, and overhead. A small AI team in Switzerland costs CHF 30K-80K/month.',
      input_type: 'number',
      default_value: 40000,
      min: 1000,
      max: 1000000,
      step: 5000,
      unit: 'CHF',
      parameter_key: 'fixedMonthlyCost',
    },
    {
      question_id: 'q6',
      question_text: 'What upfront investment is needed?',
      help_text: 'Include setup costs, licenses, infrastructure. Swiss AI projects typically require CHF 50K-500K upfront.',
      input_type: 'number',
      default_value: 100000,
      min: 0,
      max: 5000000,
      step: 10000,
      unit: 'CHF',
      parameter_key: 'upfrontCost',
    },
    {
      question_id: 'q7',
      question_text: 'When do you expect to launch (months from now)?',
      help_text: 'AI MVPs typically take 3-6 months. Full enterprise rollouts take 6-12 months.',
      input_type: 'slider',
      default_value: 4,
      min: 1,
      max: 12,
      step: 1,
      unit: 'months',
      parameter_key: 'launchMonth',
    },
    {
      question_id: 'q8',
      question_text: 'What is the available budget for this initiative?',
      help_text: 'This is the total cash available to fund the initiative until it becomes self-sustaining.',
      input_type: 'number',
      default_value: 300000,
      min: 10000,
      max: 10000000,
      step: 50000,
      unit: 'CHF',
      parameter_key: 'startingBudget',
    },
  ],
  churn_reduction: [
    {
      question_id: 'q1',
      question_text: 'What type of revenue impact does this initiative create?',
      help_text: 'Most corporate AI initiatives fall into one of these categories.',
      input_type: 'select',
      options: ['New revenue stream', 'Cost savings / efficiency', 'Churn reduction / retention'],
      default_value: 'Churn reduction / retention',
      parameter_key: 'revenueModel',
      mapValue: v => ({ 'New revenue stream': 'new_revenue', 'Cost savings / efficiency': 'cost_savings', 'Churn reduction / retention': 'churn_reduction' }[v] || 'churn_reduction'),
    },
    {
      question_id: 'q2',
      question_text: 'How large is your current subscriber base?',
      help_text: 'Media subscription services in Europe typically have 50K-2M subscribers.',
      input_type: 'number',
      default_value: 100000,
      min: 100,
      max: 50000000,
      step: 10000,
      unit: 'subscribers',
      parameter_key: 'subscriberBase',
    },
    {
      question_id: 'q3',
      question_text: 'What is your current monthly churn rate?',
      help_text: 'Media subscription services in Europe typically see 4-8% monthly churn. Banking services see 1-3%.',
      input_type: 'slider',
      default_value: 6,
      min: 1,
      max: 20,
      step: 0.5,
      unit: '%',
      parameter_key: 'oldChurn',
      mapValue: v => v / 100,
    },
    {
      question_id: 'q4',
      question_text: 'What churn rate do you target after the initiative?',
      help_text: 'AI-driven retention tools typically reduce churn by 20-40% relative to baseline.',
      input_type: 'slider',
      default_value: 4,
      min: 0.5,
      max: 15,
      step: 0.5,
      unit: '%',
      parameter_key: 'newChurn',
      mapValue: v => v / 100,
    },
    {
      question_id: 'q5',
      question_text: 'What is the average revenue per user per month?',
      help_text: 'Swiss digital subscriptions average CHF 15-50/month.',
      input_type: 'number',
      default_value: 30,
      min: 1,
      max: 10000,
      step: 5,
      unit: 'CHF',
      parameter_key: 'avgRevenuePerUser',
    },
    {
      question_id: 'q6',
      question_text: 'What are the monthly operating costs for this initiative?',
      help_text: 'Include team, infrastructure, and AI/ML platform costs.',
      input_type: 'number',
      default_value: 35000,
      min: 1000,
      max: 500000,
      step: 5000,
      unit: 'CHF',
      parameter_key: 'fixedMonthlyCost',
    },
    {
      question_id: 'q7',
      question_text: 'What upfront investment is needed and when do you launch?',
      help_text: 'Typical churn reduction projects: CHF 50K-200K upfront, 3-6 month build.',
      input_type: 'number',
      default_value: 80000,
      min: 0,
      max: 2000000,
      step: 10000,
      unit: 'CHF',
      parameter_key: 'upfrontCost',
    },
    {
      question_id: 'q8',
      question_text: 'What is the available budget for this initiative?',
      help_text: 'Total cash available to fund the project until break-even.',
      input_type: 'number',
      default_value: 250000,
      min: 10000,
      max: 10000000,
      step: 50000,
      unit: 'CHF',
      parameter_key: 'startingBudget',
    },
  ],
  cost_savings: [
    {
      question_id: 'q1',
      question_text: 'What type of revenue impact does this initiative create?',
      help_text: 'Most corporate AI initiatives fall into one of these categories.',
      input_type: 'select',
      options: ['New revenue stream', 'Cost savings / efficiency', 'Churn reduction / retention'],
      default_value: 'Cost savings / efficiency',
      parameter_key: 'revenueModel',
      mapValue: v => ({ 'New revenue stream': 'new_revenue', 'Cost savings / efficiency': 'cost_savings', 'Churn reduction / retention': 'churn_reduction' }[v] || 'cost_savings'),
    },
    {
      question_id: 'q2',
      question_text: 'What is the current monthly cost of the process you want to optimize?',
      help_text: 'Include labor, tools, and overhead. Swiss operational costs for a mid-size process: CHF 50K-300K/month.',
      input_type: 'number',
      default_value: 150000,
      min: 5000,
      max: 5000000,
      step: 10000,
      unit: 'CHF',
      parameter_key: 'currentMonthlyCost',
    },
    {
      question_id: 'q3',
      question_text: 'What percentage of costs do you expect to save?',
      help_text: 'AI automation typically saves 15-40% on operational costs. Conservative estimate: 20%.',
      input_type: 'slider',
      default_value: 25,
      min: 5,
      max: 60,
      step: 5,
      unit: '%',
      parameter_key: 'savingsPercentage',
      mapValue: v => v / 100,
    },
    {
      question_id: 'q4',
      question_text: 'What are the monthly costs to build and maintain the solution?',
      help_text: 'AI/automation teams in Switzerland: CHF 25K-60K/month for a small team.',
      input_type: 'number',
      default_value: 30000,
      min: 1000,
      max: 500000,
      step: 5000,
      unit: 'CHF',
      parameter_key: 'fixedMonthlyCost',
    },
    {
      question_id: 'q5',
      question_text: 'What upfront investment is needed?',
      help_text: 'Include software licenses, integration costs, training. Typical: CHF 50K-300K.',
      input_type: 'number',
      default_value: 75000,
      min: 0,
      max: 2000000,
      step: 10000,
      unit: 'CHF',
      parameter_key: 'upfrontCost',
    },
    {
      question_id: 'q6',
      question_text: 'When do you expect the solution to be operational?',
      help_text: 'Process automation MVPs: 2-4 months. Full rollout: 4-8 months.',
      input_type: 'slider',
      default_value: 3,
      min: 1,
      max: 12,
      step: 1,
      unit: 'months',
      parameter_key: 'launchMonth',
    },
    {
      question_id: 'q7',
      question_text: 'What is the available budget for this initiative?',
      help_text: 'Total cash available to fund the project until it pays for itself.',
      input_type: 'number',
      default_value: 200000,
      min: 10000,
      max: 10000000,
      step: 50000,
      unit: 'CHF',
      parameter_key: 'startingBudget',
    },
  ],
};

function detectBusinessModel(description) {
  const text = description.toLowerCase();
  if (/churn|retention|subscriber|reduce.*loss|keep.*customer/i.test(text)) return 'churn_reduction';
  if (/cost.*sav|efficien|automat|internal.*tool|optimi|reduce.*cost|streamlin/i.test(text)) return 'cost_savings';
  return 'new_revenue';
}

export function getNextFallbackQuestion(description, answers) {
  const detectedModel = answers.length === 0
    ? detectBusinessModel(description)
    : (answers[0]?.mappedValue || detectBusinessModel(description));

  const flow = questionFlows[detectedModel] || questionFlows.new_revenue;

  if (answers.length >= flow.length) {
    // Build final parameters from answers
    const finalParams = { revenueModel: detectedModel };
    answers.forEach(a => {
      if (a.parameterKey) {
        finalParams[a.parameterKey] = a.mappedValue !== undefined ? a.mappedValue : a.value;
      }
    });
    return {
      complete: true,
      summary: `Business case analysis for: ${description}`,
      final_parameters: finalParams,
    };
  }

  return flow[answers.length];
}
